services:
  - type: web
    name: campusone-fullstack
    env: node
    branch: master
    buildCommand: "npm install && npm run build && cd server && npm install"
    startCommand: "cd server && npm start"
    plan: starter
