services:
  - type: web
    name: campusone-fullstack
    env: node
    branch: master
    buildCommand: "npm ci --include=dev && npm run build && cd server && npm ci --omit=dev"
    startCommand: "cd server && npm start"
    plan: starter
