services:
  - type: web
    name: campusone-fullstack
    env: node
    branch: master
    buildCommand: "npm ci && npm run build && cd server && npm ci"
    startCommand: "cd server && npm start"
    plan: starter
